Kura/Models/MyModels/Place.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Koora.Models.MyModels
{
    public class Place
    {
        public int id { get; set; }
        
        [Required]
        [Display(Name = "Name")]
        public string name { get; set; }

        [Required]
        [Display(Name ="Description")]
        public string description { get; set; }

        [Required]
        [Display(Name = "Location")]
        public string location { get; set; }
    }
}

Kura/Models/ViewModels/PlaceDetailViewModel.cs
using Koora.Models.MyModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Koora.Models.ViewModels
{
    public class PlaceDetailViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Location")]
        public string Location { get; set; }

        public int RateId { get; set; }

        [Required]
        [Range(0, 5)]
        public int Star {  get; set; }

        [StringLength(100, MinimumLength = 5)]
        [Display(Name = "Comment")]
        public string Comment { get; set; }
        

        [StringLength(128)]
        public string UserId { get; set; }
        public int PlaceId { get; set; }


    }
}

Kura/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Koora.Models;
using Koora.Models.MyModels;

namespace Koora.Controllers
{
    [Authorize]
    public class PlacesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Places
        public ActionResult Index()
        {
            return View(db.Places.ToList());
        }

        public ActionResult PlaceDetail(int id)
        {
            var place = db.Places.First(m => m.id == id);
            return View("Place-detail", place);
        }

        // GET: Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // GET: Places/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Places/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,description,location")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Places.Add(place);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(place);
        }

        // GET: Places/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,description,location")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Entry(place).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(place);
        }

        // GET: Places/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Place place = db.Places.Find(id);
            db.Places.Remove(place);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Kura/Views/Places/CommentSection.cshtml
@model Koora.Models.MyModels.Rate




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kura/Views/Places/Create.cshtml
@model Koora.Models.MyModels.Place

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Place</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kura/Views/Places/Delete.cshtml
@model Koora.Models.MyModels.Place

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Place</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Kura/Views/Places/Edit.cshtml
@model Koora.Models.MyModels.Place

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Place</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kura/Views/Places/Index.cshtml
@model IEnumerable<Koora.Models.MyModels.Place>

@{
    ViewBag.Title = "Place";
    ViewBag.idN = "home-p";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--====================================================
                       HOME-P
======================================================-->
<div id="@ViewBag.idN" class="home-p pages-head1 text-center">
    <div class="container">
        <h1 class="wow fadeInUp" data-wow-delay="0.1s">Places On Campus</h1>
        <p>Live</p>
    </div><!--/end container-->
</div>

<!--====================================================
                        news-p1
======================================================-->
<section id="news-p1" class="news-p1" style="min-height:50vh">
    <div class="container">
        <div class="row">
            <div class="card-columns">
                @foreach (var m in Model)
                {
                <div class="card">
                    <div class="desc-comp-offer-cont">
                        <div class="thumbnail-blogs">
                            <div class="caption">
                                <i class="fa fa-chain"></i>
                            </div>
                            <img src="img/news/news-6.jpg" class="img-fluid" alt="...">
                        </div>
                        <h3>Modified hand-cart with steering</h3>
                        <p class="desc">The idea is to incorporate easy steering mechanism and brakes to make turning hand carts easy and arrest slide on inclines. </p>
                        @Html.ActionLink("RATE", "PlaceDetail", "Places", new {id=m.id }, new { @class = "fa fa-arrow-circle-o-right" })
                    </div>
                </div>
                }
                
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        $("#placeIco").addClass("activeNav");
    </script>
    
    }

Kura/Views/Places/Place-detail.cshtml
@model Koora.Models.MyModels.Place

@{
    ViewBag.Title = "Rate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="single-news-p1" class="single-news-p1">
    <div class="container">
        <div class="row">
            <!-- left news details -->
            @*<div class="col-md-2"></div>*@
            <div class="col-md-12">
                <div class="single-news-p1-cont">
                    <div class="single-news-img">
                        <img src="~/Content/img/news/news-1.jpg" alt="" class="img-fluid">
                    </div>
                    <div class="single-news-desc">
                        <h3>@Model.name</h3>
                        <ul class="list-inline">
                            <li>Posted: <span class="text-theme-colored2"> 9/9/2018</span></li>
                            <li>By: <span class="text-theme-colored2">Admin</span></li>
                            <li><i class="fa fa-comments-o"></i> 1 comments</li>
                        </ul>
                        <hr>
                        <div class="bg-light-gray">
                            <p>@Model.description</p>
              
                        </div>

                    </div>
                </div>
                <hr>
            </div>
            <div class="comments-container col-md-7">
                <ul id="comments-list" class="comments-list">
                    <li>
                        <div class="comment-main-level">
                            <!-- Avatar -->
                            <div class="comment-avatar"><img src="~/Content/img/news/news-1.jpg" alt=""></div>
                            <!-- Contenedor del Comentario -->
                            <div class="comment-box">
                                <div class="comment-head">
                                    <h6 class="comment-name by-author"><a href="#">John Boss</a></h6>
                                    <span>before 20 minutes</span>
                                    <i class="fa fa-reply"></i>
                                    <i class="fa fa-heart"></i>
                                </div>
                                <div class="comment-content">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit omnis animi et iure laudantium vitae, praesentium optio, sapiente distinctio illo?
                                </div>
                            </div>
                        </div>
                        <!-- Respuestas de los comentarios -->
                        <ul class="comments-list reply-list">
                            <li>
                                <!-- Avatar -->
                                <div class="comment-avatar"><img src="img/client/avatar-6.jpg" alt=""></div>
                                <!-- Contenedor del Comentario -->
                                <div class="comment-box sub-comment-box">
                                    <div class="comment-head">
                                        <h6 class="comment-name"><a href="#">Tresa Ben</a></h6>
                                        <span>hace 10 minutos</span>
                                        <i class="fa fa-reply"></i>
                                        <i class="fa fa-heart"></i>
                                    </div>
                                    <div class="comment-content">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit omnis animi et iure laudantium vitae, praesentium optio, sapiente distinctio illo?
                                    </div>
                                </div>
                            </li>

                            <li>
                                <!-- Avatar -->
                                <div class="comment-avatar"><img src="img/client/avatar-2.jpg" alt=""></div>
                                <!-- Contenedor del Comentario -->
                                <div class="comment-box sub-comment-box">
                                    <div class="comment-head">
                                        <h6 class="comment-name by-author"><a href="#">John Boss</a></h6>
                                        <span>before 10 minutes</span>
                                        <i class="fa fa-reply"></i>
                                        <i class="fa fa-heart"></i>
                                    </div>
                                    <div class="comment-content">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit omnis animi et iure laudantium vitae, praesentium optio, sapiente distinctio illo?
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <div class="comment-main-level">
                            <!-- Avatar -->
                            <div class="comment-avatar"><img src="img/client/avatar-1.jpg" alt=""></div>
                            <!-- Contenedor del Comentario -->
                            <div class="comment-box">
                                <div class="comment-head">
                                    <h6 class="comment-name"><a href="#">Blensan Trul</a></h6>
                                    <span>before 10 minutes</span>
                                    <i class="fa fa-reply"></i>
                                    <i class="fa fa-heart"></i>
                                </div>
                                <div class="comment-content">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit omnis animi et iure laudantium vitae, praesentium optio, sapiente distinctio illo?
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            @*<div class="col-md-4></div>*@
            <div class="col-md-8">
                <div class="comment-box-sn">
                    <h5>Leave a Reply</h5>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary()
                        <div class="form-group">
                            @Html.TextAreaFor(m => m.description, new { placeholder = "Comment" })
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.description)
                        </div>

                        <input type="text" name="text" placeholder="Name" class="form-control"><br>
                        <button class="btn btn-general btn-green" style="width: 100%;" role="button">Send</button>
                    }

                </div>
            </div>
            
        </div>
    </div>
</section>